// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pccuyjysvuwiebuvgyoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjY3V5anlzdnV3aWVidXZneW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTc4NjksImV4cCI6MjA2NjMzMzg2OX0.hG87r6orSjN4kzYLJ3qk81x790MS4Maxcw9OHbIfXmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);